### ISSUE TITLE
Font Awesome SVG icons breaking layout

### ISSUE THREAD

**Issue by weiserhei** [azouaoui-med/pro-sidebar-template#2]
I have implemented your sidebar into my project and noticed with the current npm Font Awesome package the icons are replaced by SVG.

**The CSS classes targeting only the `<i>`-element, the layout breaks and animations dont work.** 

Can you provide a fix for that? Ive tried myself but just replacing the `i`-selectors in CSS doesnt do the job.

**Comment by azouaoui-med** [comment]
In the current font-awesome release you can actually choose whether to use the Web Fonts with CSS or SVG with JS, in my case i used the first method in the bootstrap4 version, so you are not restricted to only svg. 

That being said if you want to use svg with js, you may wanna change a few things, because the i element like you mentioned is being replaced by an svg element which makes the css selectors not work.

 And changing the i selectors with svg selector will not solve the problem,

The solution is to wrap the i element inside another element, a span for example : 

`  <span class="svg-icon"><i class="fa fa-tachometer-alt"></i></span>`

and change the selectors from `i` to `span.svg-icon`

```
.sidebar-wrapper .sidebar-menu ul li a span.svg-icon {
    margin-right: 10px;
    font-size: 12px;
    line-height: 30px;
    width: 30px;
    height: 30px;
    text-align: center;
    border-radius: 4px;
    display: inline-block;
}
```
and for the animation you will need to apply it on the svg 

```
.sidebar-wrapper .sidebar-menu ul li a:hover> span.svg-icon svg {
    animation: swing ease-in-out .5s 1 alternate;
}
```
I hope this helps you resolve the problem 😄

**Comment by weiserhei** [comment]
> you can actually choose whether to use the Web Fonts with CSS or SVG

Theoretically you are correct, except I cant. Any Fontawesome configuration setting has no effect in my project, thats why I came up with the issue :-(

Your presented solution did the trick, thank you very much. Ive replaced every icon with svg and it looks almost like the original one, except on small font-sizes the svg-icons dont look as bold as the css ones, I guess due to aliasing.
